# Generated by Django 2.1.5 on 2019-02-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brewery', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('style', models.CharField(max_length=255)),
                ('abv', models.CharField(max_length=10)),
                ('ibu', models.CharField(max_length=10)),
            ],
        ),
    ]
