# Generated by Django 2.1.5 on 2019-02-04 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BeerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 21, 11, 16, 827209, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
